// Generated by CoffeeScript 1.3.3
(function() {
  var api, file, http, site;

  http = require('http');

  file = require('node-static');

  site = new file.Server('.');

  http.createServer(function(request, response) {
    return request.addListener('end', function() {
      return site.serve(request, response);
    });
  }).listen(8080);

}).call(this);
